<?php

namespace AppBundle\Repository;

/**
 * ECategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ECategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
