<?php

namespace AppBundle\Repository;

/**
 * FCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
