<?php

namespace AppBundle\Repository;

/**
 * FoundationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoundationRepository extends \Doctrine\ORM\EntityRepository
{
}
