event_index:
    path:     /
    defaults: { _controller: "AppBundle:Event:index" }
    methods:  GET

event_new:
    path:     /new
    defaults: { _controller: "AppBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Event:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Event:delete" }

event_participants:
    path:     /participants
    defaults: { _controller: "AppBundle:Event:participants" }
    methods:  GET